
   
[package]
name = "swift-rs"
version = "0.1.0"
description = "Connect Rust & Swift with ease!"
authors = ["you"]
license = ""
repository = ""
default-run = "swift-rs"
edition = "2018"
build = "src/build.rs"

[dependencies]
objc = "0.2.7"
cocoa = "0.24.0"
objc-foundation = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13.0"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
